language: python
python:
  - "3.8"
cache: pip
addons:
  postgresql: "9.5"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database my_databse;' -U postgres
script:
  - python -m pytest tests -v

