version: '3'

services:
  database:
    image: 'postgres'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DBNAME}
    ports:
      - '5432:5432'
    volumes:
      - '${DATABASE_LOCAL_PATH}:/var/lib/postgresql/data/'
